### ISSUE TITLE
ERROR when Running the template with account restriction to us-east-1

### ISSUE THREAD

**Issue by aa2858** [aws-samples/amazon-rekognition-engagement-meter#39]
`
2019-09-25T09:27:35.212Z fb704d38-82bf-48d5-9a1c-07b62cb6eff0 { AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:585:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'Access Denied',
code: 'AccessDenied',
region: 'eu-west-1',
time: 2019-09-25T09:27:35.211Z,
requestId: 'xxxxxxxxxx',
extendedRequestId: 'xxxxxxxxxx',
cfId: undefined,
statusCode: 403,
retryable: false,
retryDelay: 83.26157207853085 }`

**Comment by matteofigus** [comment]
Thanks for your submission @aa2858 - we are looking into that.

**Comment by matteofigus** [comment]
@aa2858 we just made a change to the release pipeline that should address your issue.

Can you please try to redeploy the stack by using one of the buttons on the README? 

Thanks.

**Comment by aa2858** [comment]
Thank you.  The issue has been resolved and I have been able to progress forward but not completely done.

I cannot directly use the readme button because I need to customize the template to work in our environment.  I have limited admin rights and I have to pre-create one of the roles.

The current issue is that cfn is complaining about lambda codeuri which I have looked up and the resolution I have is to package the code with `sam` which generate the code location on s3 and update the template.

Just wanted to check if this is correct.  The change cycle takes time because of cloudfront. 

Thanks,
Adams

**Comment by matteofigus** [comment]
Thanks @aa2858,

In order to customise the back-end code, here is my recommendation.

If you need to change the lambda:
1. You need a S3 bucket to do the packaging. That wasn't needed before, but we changed that to improve the reliability. The S3 bucket needs to be in the same region you'll deploy the stack.
2. Run `npm install` to start
3. Make changes to the `/src/cfn/template.yaml` file and the lambdas
4. Run `npm run build` (this will create a file in templates/template.yaml that refers to the local lambdas)
5. Run `aws cloudformation package --template-file templates/template.yaml --s3-bucket <YOUR S3 BUCKET> --output-template-file templates/packaged.yaml` (this can be done with the aws cli, the sam cli is actually not needed)
6. Now you can deploy your packaged template `aws cloudformation deploy --template-file templates/packaged.yaml --stack-name <YOUR STACK NAME>`

I hope it makes sense. If you look into the `packaged.yaml` file after step 5, you'll see that the lambda paths switch from local paths to s3 paths. 

If you don't need to change the lambda, it's a bit easier:
1. Get the template url from one of the links in the README. For instance, the `us-east-1` is https://solution-builders-us-east-1.s3.us-east-1.amazonaws.com/amazon-rekognition-engagement-meter/latest/main.template
2. Edit that file as you wish
3. Deploy with `aws cloudformation deploy --template-file main.template --stack-name <YOUR STACK NAME>`

I hope it makes sense.

**Comment by matteofigus** [comment]
(I am closing now given you mentioned the issue may be different, but feel free to re-open if that's not the case).
